### PR TITLE
Configure and enable watchdog just before jumping to the application firmware

### PR DESCRIPTION
**Pull request by JF002**
This PR enables the watchdog just before jumping to the application bootloader. In case of issue with the new firmware, and if this firmware does not refresh it, the watchdog will reset the CPU, allowing MCUBoot to rollback to the previous version of the firmware.

This PR will help prevent the user from bricking their device by uploading a non-working firmware via the OTA.

Note that if this PR is merged, the application firmware will have to refresh the watchdog register periodically (max delay is ~7 seconds).

Here is the code to refresh the watchdog:
`NRF_WDT->RR[0] = WDT_RR_RR_Reload;`

### CODE REVIEW

**Comment by lupyuen** [comment]
Yep merged thanks!

How would we test this hmmm....

**Comment by JF002** [comment]
I did test it by building a custom bootloader that does not refresh the watchdog :)

This is how I found this issue : generate the DFU file with the standalone firmware (built to start @0x0 instead of 0x8000). The bootloader jumps, but the vector table is incorrect and ... cpu does nothing. In this case, the watchdog will reset and mcuboot will rollback.

**Comment by JF002** [comment]
Here is a test scenario. It uses 2 new files (I had to compress them into ZIP files for Github...):
 - [bootloader_with_watchdog.zip](https://github.com/lupyuen/pinetime-rust-mynewt/files/5058620/bootloader_with_watchdog.zip) : the bootloader built from this PR
 - [dfu-BAD.zip](https://github.com/lupyuen/pinetime-rust-mynewt/files/5058627/dfu-BAD.zip) : A DFU file generated from the standalone version of InfiniTime (https://github.com/JF002/Pinetime/releases/download/0.7.1/pinetime-app.bin). This firmware is built to run from offset 0x0 and won't run correctly when flashed at offset 0x8000 by OTA.

1. Using the current version of the bootloader (https://github.com/JF002/Pinetime/releases/download/0.7.1/bootloader.hex)
     - Flash the bootloader and the image of InfiniTime 0.7.1 (https://github.com/JF002/Pinetime/releases/download/0.7.1/pinetime-mcuboot-app-image.hex)
    - Reset and notice that it's working fine
    - OTA the dfu-BAD.img firmware
    - Reset
    - Notice that the screen displays the boot logo, and that the firmware does not run, the system is locked and there is no way to reset the CPU.

2. Using the new version of the bootloader (bootloader_with_watchdog.img)
    - Flash the new bootloader and the image of InfiniTime 0.7.1 (https://github.com/JF002/Pinetime/releases/download/0.7.1/pinetime-mcuboot-app-image.hex)
    - OTA the dfu-BAD.img firmware
    - Reset
    - Notice that the bootloader displays the boot logo, take some time, then the screen blinks (it's the reset from the watchdog) and finally, the original firmware runs again, meaning that MCUboot reverted to the old firmware. Victory :+1:

**Comment by lupyuen** [comment]
Great Job! :-) Wonder if we should use the Logo Loader as a simple test case, since it's a really simple firmware. 

And we should recruit some beta testers to help with Regression Testing whenever we update the bootloader (since it's so mission critical).

Should the pinetime-updater utility have an option for flashing Beta Bootloader for testing? Hmmm...

**Comment by endian-albin** [comment]
Hypnos is now [compatible](https://github.com/endian-albin/pinetime-hypnos/pull/71/commits/d2d7e3171d08c5d6336ec519c0ba5d2e223561bb) with this watchdog.

**Comment by lupyuen** [comment]
Awesome! :-)

**Pull request merged**
